# Importing libraries

In [281]:
import pandas as pd
import numpy as np

import string
import nltk
from nltk.corpus import stopwords
#from sklearn.feature_extraction.text import CountVectorizer

# loading train and test file

In [282]:
train = pd.read_csv("traindata.csv")
test= pd.read_csv("testdata.csv")
train=train.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4','Unnamed: 4','Unnamed: 5'],axis=1)

In [283]:
train.head()

category                                               text
0   science  Outer space is not friendly to life. Extreme t...
1    sports  Tennis, original name lawn tennis, game in whi...
2  business  One woman who frequently flew on Southwest was...
3     covid  In December 2019, almost seven years after the...
4   science  Any life-forms that somehow find themselves in...

In [284]:
test.head()

category                                               text
0  science  He estimates that 1,000-micrometer pellets cou...
1  science  “That’s enough time to potentially get to Mars...
2  science  How exactly clumps of microbes might get expel...
3  science  The microbes might get kicked up by small mete...
4  science  Someday, if microbial life is ever discovered ...

# Splitting into words

In [285]:
u1 = train.text.str.split(expand=True).stack()
u2 = test.text.str.split(expand=True).stack()
u=u1.append(u2)

In [286]:
print(u[:10])

0  0            Outer
   1            space
   2               is
   3              not
   4         friendly
   5               to
   6            life.
   7          Extreme
   8    temperatures,
   9              low
dtype: object


In [287]:
words=u.values

In [288]:
print(words[:10])

['Outer' 'space' 'is' 'not' 'friendly' 'to' 'life.' 'Extreme'
 'temperatures,' 'low']


# Removing punctuation

In [289]:
words=words.tolist()

In [290]:
table = str.maketrans('', '', string.punctuation)
final = [w.translate(table) for w in words]

In [291]:
print(final[:100])

['Outer', 'space', 'is', 'not', 'friendly', 'to', 'life', 'Extreme', 'temperatures', 'low', 'pressure', 'and', 'radiation', 'can', 'quickly', 'degrade', 'cell', 'membranes', 'and', 'destroy', 'DNA', 'Tennis', 'original', 'name', 'lawn', 'tennis', 'game', 'in', 'which', 'two', 'opposing', 'players', 'singles', 'or', 'pairs', 'of', 'players', 'doubles', 'use', 'tautly', 'strung', 'rackets', 'to', 'hit', 'a', 'ball', 'of', 'specified', 'size', 'weight', 'and', 'bounce', 'over', 'a', 'net', 'on', 'a', 'rectangular', 'court', 'One', 'woman', 'who', 'frequently', 'flew', 'on', 'Southwest', 'was', 'constantly', 'disappointed', 'with', 'every', 'aspect', 'of', 'the', 'company’s', 'operation', 'In', 'fact', 'she', 'became', 'known', 'as', 'the', '“Pen', 'Pal”', 'because', 'after', 'every', 'flight', 'she', 'wrote', 'in', 'with', 'a', 'complaint', 'In', 'December', '2019', 'almost', 'seven']


In [292]:
words = [word.lower() for word in final]

# Removing stop words

In [293]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [294]:
stop_words = stopwords.words('english')
print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [295]:
filtered_sentence = [] 
  
for w in words: 
    if w not in stop_words: 
        filtered_sentence.append(w)

In [296]:
len(filtered_sentence)

1611

In [297]:
filtered_sentence=np.unique(np.array(filtered_sentence))
filtered_sentence_final=[]
for word in filtered_sentence:
    if not word.isdigit():
        filtered_sentence_final.append(word)
        

In [298]:
filtered_sentence=filtered_sentence_final
len(filtered_sentence)

929

In [299]:
print(filtered_sentence[:200])

['', '1000micrometer', '1000micrometers', '100micrometerthick', '12th–13thcentury', '15–30', '1960s', '1970s', '2019ncov', '21st', '30–15', 'abandon', 'ability', 'able', 'abuse', 'abusive', 'accidentally', 'according', 'ace2', 'across', 'activities', 'acute', 'adapt', 'added', 'adds', 'affected', 'affixed', 'agent', 'agreed', 'akihiko', 'allowed', 'allows', 'almost', 'also', 'alternate', 'although', 'always', 'amateurs', 'among', 'ancient', 'andor', 'angiotensinconverting', 'angles', 'animal', 'animals', 'antihiv', 'antivirals', 'anything', 'appeal', 'appeared', 'appears', 'april', 'aren’t', 'argues', 'around', 'arrived', 'artificial', 'asked', 'aspect', 'asphalt', 'assign', 'associations', 'astrobiologist', 'astronaut', 'astronautical', 'attack', 'attempts', 'attendant', 'attitude', 'attracted', 'australia', 'available', 'avian', 'awarded', 'away', 'back', 'bacteria', 'bacteriato', 'bad', 'balances', 'ball', 'balls', 'band', 'baseline', 'bats', 'became', 'began', 'beginning', 'behind'

# Vocabulary creation

In [300]:
z=0
vocabulary={}
for word in filtered_sentence:
    vocabulary[word]=z
    z=z+1


In [301]:
print(vocabulary)

{'': 0, '1000micrometer': 1, '1000micrometers': 2, '100micrometerthick': 3, '12th–13thcentury': 4, '15–30': 5, '1960s': 6, '1970s': 7, '2019ncov': 8, '21st': 9, '30–15': 10, 'abandon': 11, 'ability': 12, 'able': 13, 'abuse': 14, 'abusive': 15, 'accidentally': 16, 'according': 17, 'ace2': 18, 'across': 19, 'activities': 20, 'acute': 21, 'adapt': 22, 'added': 23, 'adds': 24, 'affected': 25, 'affixed': 26, 'agent': 27, 'agreed': 28, 'akihiko': 29, 'allowed': 30, 'allows': 31, 'almost': 32, 'also': 33, 'alternate': 34, 'although': 35, 'always': 36, 'amateurs': 37, 'among': 38, 'ancient': 39, 'andor': 40, 'angiotensinconverting': 41, 'angles': 42, 'animal': 43, 'animals': 44, 'antihiv': 45, 'antivirals': 46, 'anything': 47, 'appeal': 48, 'appeared': 49, 'appears': 50, 'april': 51, 'aren’t': 52, 'argues': 53, 'around': 54, 'arrived': 55, 'artificial': 56, 'asked': 57, 'aspect': 58, 'asphalt': 59, 'assign': 60, 'associations': 61, 'astrobiologist': 62, 'astronaut': 63, 'astronautical': 64, 'a

# Calculating the prior distribution of the labels

In [302]:
np.unique(train.category)

array(['business', 'covid', 'science', 'sports'], dtype=object)

In [303]:
total_labels=len(train)

In [304]:
business=train['category'][train['category']=='business'].count()
covid=train['category'][train['category']=='covid'].count()
science=train['category'][train['category']=='science'].count()
sports=train['category'][train['category']=='sports'].count()

In [305]:
pr_business=business/total_labels#prior distribution of business
pr_covid=covid/total_labels#prior distribution of covid
pr_science=science/total_labels#prior distribution of science
pr_sports=sports/total_labels#prior distribution of sports

In [306]:
print(pr_business)
print(pr_covid)
print(pr_science)
print(pr_sports)

0.2375
0.2625
0.25
0.25


# Preprocessing the train and test text

In [307]:
def preprocess(x):
    x=x.split()
    table = str.maketrans('', '', string.punctuation)
    x = [w.translate(table) for w in x]
    x = [word.lower() for word in x]
    final = [] 
    for w in x: 
        if w not in stop_words: 
            final.append(w)
    x=np.array(final)
    filtered_sentence_final=[]
    for word in x:
        if not word.isdigit():
            filtered_sentence_final.append(word)
    x=np.unique(filtered_sentence_final)
    return x

In [308]:
def word_to_vocabulary(x):
    final=[]
    for word in x:
        final.append(vocabulary[word])
    return final

In [309]:
train.text[0]

'Outer space is not friendly to life. Extreme temperatures, low pressure and radiation can quickly degrade cell membranes and destroy DNA.'

In [310]:
preprocess(train.text[0])

array(['cell', 'degrade', 'destroy', 'dna', 'extreme', 'friendly', 'life',
       'low', 'membranes', 'outer', 'pressure', 'quickly', 'radiation',
       'space', 'temperatures'], dtype='<U12')

In [311]:
word_to_vocabulary(preprocess(train.text[0]))

[122, 212, 225, 242, 287, 327, 454, 470, 498, 567, 614, 629, 634, 745, 799]

In [312]:
test.text[0]

'He estimates that 1,000-micrometer pellets could survive eight years floating through space.'

In [313]:
preprocess(test.text[0])

array(['1000micrometer', 'could', 'eight', 'estimates', 'floating',
       'pellets', 'space', 'survive', 'years'], dtype='<U14')

In [314]:
word_to_vocabulary(preprocess(test.text[0]))

[1, 185, 256, 270, 312, 583, 745, 785, 906]

### Calculating the class-conditional probabilities of each word in the vocabulary, for each topic

In [315]:
classes=['business', 'covid', 'science', 'sports']
class1=[0]*len(vocabulary)
class2=[0]*len(vocabulary)
class3=[0]*len(vocabulary)
class4=[0]*len(vocabulary)

In [316]:
for i,j in enumerate(train.category):
    x=train.text[i]
    words=preprocess(x)
    words_vec=word_to_vocabulary(words)
    if j==classes[0]:
        for x in words_vec:
            class1[x]=class1[x]+1
    if j==classes[1]:
        for x in words_vec:
            class2[x]=class2[x]+1
    if j==classes[2]:
        for x in words_vec:
            class3[x]=class3[x]+1
    if j==classes[3]:
        for x in words_vec:
            class4[x]=class4[x]+1
class1=class1/business
class2=class2/covid
class3=class3/science
class4=class4/sports

        

# Replacing zero probability with 0.1

In [317]:
type(class1)

numpy.ndarray

In [318]:
class1[class1==0] = 0.1
class2[class2==0] = 0.1
class3[class3==0] = 0.1
class4[class4==0] = 0.1

In [319]:
print(class1)

[0.10526316 0.1        0.1        0.1        0.1        0.1
 0.1        0.1        0.1        0.1        0.1        0.05263158
 0.1        0.1        0.05263158 0.10526316 0.1        0.1
 0.1        0.1        0.1        0.1        0.1        0.1
 0.1        0.1        0.1        0.1        0.1        0.1
 0.1        0.1        0.1        0.10526316 0.1        0.1
 0.21052632 0.1        0.05263158 0.1        0.1        0.1
 0.1        0.1        0.1        0.1        0.1        0.05263158
 0.1        0.1        0.1        0.1        0.05263158 0.05263158
 0.1        0.05263158 0.1        0.1        0.05263158 0.1
 0.05263158 0.1        0.1        0.1        0.1        0.1
 0.1        0.1        0.05263158 0.1        0.1        0.1
 0.1        0.1        0.1        0.10526316 0.1        0.1
 0.21052632 0.05263158 0.1        0.1        0.1        0.1
 0.1        0.05263158 0.1        0.1        0.1        0.05263158
 0.1        0.10526316 0.05263158 0.1        0.1        0.05263158
 0.1 

# For each test sentence, creating the posterior distribution over the labels

In [320]:
labels=np.array(test.category)

In [321]:
len(labels)

20

In [322]:
def cal_prob(x,class_no):
    prob=1
    for i in x:
        prob=prob*class_no[i]
    return prob

In [323]:
class_predicted=[]
confid=[]
for x in test.text:
    words=preprocess(x)
    words_vec=word_to_vocabulary(words)
    class1_pred=pr_business*cal_prob(words_vec,class1)
    class2_pred=pr_covid*cal_prob(words_vec,class2)
    class3_pred=pr_science*cal_prob(words_vec,class3)
    class4_pred=pr_sports*cal_prob(words_vec,class4)
    class_total=class1_pred+class2_pred+class3_pred+class4_pred
    v=np.argmax([class1_pred,class2_pred,class3_pred,class4_pred])
    if v==0:
        class_predicted.append('business')
        confid.append(class1_pred/class_total)
    if v==1:
        class_predicted.append('covid')
        confid.append(class2_pred/class_total)
    if v==2:
        class_predicted.append('science')
        confid.append(class3_pred/class_total)
    if v==3:
        class_predicted.append('sports')
        confid.append(class4_pred/class_total)

In [324]:
result=class_predicted==labels
result=list(result)

In [325]:
correct_predicted=result.count(True)

In [326]:
accuracy=correct_predicted/20

# Accuracy

In [327]:
accuracy

0.55

# Confidence

In [328]:
confid

[0.8090614886731392,
 0.44096023707440885,
 0.9148458446738739,
 0.548119086083545,
 0.27999999999999997,
 0.6535222569296971,
 0.31831419128955213,
 0.42857142857142855,
 0.28965517241379307,
 0.4347945518089499,
 0.9724543929646967,
 0.408371618172537,
 0.3169181890389198,
 0.293598233995585,
 0.9720477892379843,
 0.6602839220864972,
 0.2914591538212116,
 0.3579325698532964,
 0.47413704615734104,
 0.5906674542232723]

# Using library

In [329]:
from sklearn.feature_extraction.text import CountVectorizer
# list of text documents

# create the transform
vectorizer = CountVectorizer()

# tokenize and build vocab
vectorizer.fit(filtered_sentence)
print(len(vectorizer.vocabulary_))
vocabulary=vectorizer.vocabulary_

903


In [330]:
def z(x):
    x=x.split()
    table = str.maketrans('', '', string.punctuation)
    x = [w.translate(table) for w in x]
    x = [word.lower() for word in x]
    final = [] 
    for w in x: 
        if w not in stop_words: 
            final.append(w)
    x=np.array(final)
    filtered_sentence_final=[]
    for word in x:
        if not word.isdigit():
            filtered_sentence_final.append(word)
    x=np.unique(filtered_sentence_final)
    vectorizer = CountVectorizer()
    vectorizer.fit(x)
    return vectorizer.get_feature_names()

In [331]:
for i,j in enumerate(train.category):
    x=train.text[i]
    words=z(x)
    words_vec=word_to_vocabulary(words)
    if j==classes[0]:
        for x in words_vec:
            class1[x]=class1[x]+1
    if j==classes[1]:
        for x in words_vec:
            class2[x]=class2[x]+1
    if j==classes[2]:
        for x in words_vec:
            class3[x]=class3[x]+1
    if j==classes[3]:
        for x in words_vec:
            class4[x]=class4[x]+1
class1=class1/business
class2=class2/covid
class3=class3/science
class4=class4/sports

In [332]:
class1[class1==0] = 0.1
class2[class2==0] = 0.1
class3[class3==0] = 0.1
class4[class4==0] = 0.1

In [338]:
class_predicted=[]
confid=[]
for x in test.text:
    words=z(x)
    words_vec=word_to_vocabulary(words)
    class1_pred=pr_business*cal_prob(words_vec,class1)
    class2_pred=pr_covid*cal_prob(words_vec,class2)
    class3_pred=pr_science*cal_prob(words_vec,class3)
    class4_pred=pr_sports*cal_prob(words_vec,class4)
    class_total=class1_pred+class2_pred+class3_pred+class4_pred
    v=np.argmax([class1_pred,class2_pred,class3_pred,class4_pred])
    #print(class1_pred/class_total,class2_pred/class_total,class3_pred/class_total,class4_pred/class_total)
    if v==0:
        class_predicted.append('business')
        confid.append(class1_pred/class_total)
    if v==1:
        class_predicted.append('covid')
        confid.append(class2_pred/class_total)
    if v==2:
        class_predicted.append('science')
        confid.append(class3_pred/class_total)
    if v==3:
        class_predicted.append('sports')
        confid.append(class4_pred/class_total)

In [339]:
result=class_predicted==labels
result=list(result)
correct_predicted=result.count(True)
accuracy=correct_predicted/20

# Accuracy

In [340]:
accuracy

1.0

# Confidence

In [341]:
confid

[0.9999996754159474,
 0.7568836392641031,
 0.997989357786861,
 0.9999999931743092,
 0.9963204885270126,
 0.9999999999996689,
 1.0,
 0.9999999999227952,
 0.9989587833707586,
 0.9999968017304589,
 1.0,
 0.9999615863351414,
 0.9928664213119752,
 0.9995695174442786,
 1.0,
 0.9100388226300743,
 0.9999887100889951,
 0.9999934871310998,
 0.9999967239610472,
 0.9980410740344783]

# 2nd part

In [492]:
train = pd.read_csv("40.csv")
test= pd.read_csv("10.csv")

In [493]:
train.head()

text
0  In the midst of the COVID-19 pandemic, eating ...
1  While there are no specific foods that can hel...
2  You may not be able to share meals with friend...
3  Eating a healthy diet is not about strict limi...
4  Healthy eating doesn’t have to be overly compl...

In [494]:
test.head()

text
0  Eating healthy food is important for maintainn...
1     Following a healthy diet will boost your _____
2  Avoid eating chemical additives, added sugars ...
3  Your diet should be rich of vitamins D,K, calc...
4  The healthier the food you eat, the better you...

# Splitting into words

In [495]:
u = train.text.str.split(expand=True).stack()

print(u[:10])

words=u.values

print(words[:10])


0  0           In
   1          the
   2        midst
   3           of
   4          the
   5     COVID-19
   6    pandemic,
   7       eating
   8      healthy
   9         food
dtype: object
['In' 'the' 'midst' 'of' 'the' 'COVID-19' 'pandemic,' 'eating' 'healthy'
 'food']


# Removing punctuation

In [496]:
words=words.tolist()

table = str.maketrans('', '', string.punctuation)
final = [w.translate(table) for w in words]

print(final[:100])

words = [word.lower() for word in final]

['In', 'the', 'midst', 'of', 'the', 'COVID19', 'pandemic', 'eating', 'healthy', 'food', 'remains', 'an', 'important', 'part', 'of', 'maintaining', 'your', 'health', 'While', 'there', 'are', 'no', 'specific', 'foods', 'that', 'can', 'help', 'protect', 'you', 'from', 'the', 'virus', 'a', 'nutritious', 'diet', 'can', 'boost', 'your', 'immune', 'system', 'or', 'help', 'you', 'fight', 'off', 'symptoms', 'You', 'may', 'not', 'be', 'able', 'to', 'share', 'meals', 'with', 'friends', 'and', 'loved', 'ones', 'but', 'there', 'are', 'lots', 'of', 'other', 'ways', 'to', 'eat', 'well', 'and', 'support', 'your', 'health', 'at', 'this', 'difficult', 'time', 'Eating', 'a', 'healthy', 'diet', 'is', 'not', 'about', 'strict', 'limitations', 'staying', 'unrealistically', 'thin', 'or', 'depriving', 'yourself', 'of', 'the', 'foods', 'you', 'love', 'Rather', 'it’s', 'about']


# Removing stop words

In [497]:
nltk.download('stopwords')

stop_words = stopwords.words('english')


filtered_sentence = [] 
  
for w in words: 
    if w not in stop_words: 
        filtered_sentence.append(w)

print(len(filtered_sentence))

filtered_sentence2=np.unique(np.array(filtered_sentence))

print(len(filtered_sentence2))





577
377


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [498]:
print(filtered_sentence2[:200])

['able' 'add' 'added' 'adding' 'additives' 'advice' 'age' 'alone' 'also'
 'alternatives' 'always' 'amount' 'amounts' 'antioxidants' 'anxiety'
 'around' 'asparagus' 'avoid' 'aware' 'back' 'bacon' 'bad' 'balance'
 'beans' 'become' 'beets' 'bell' 'better' 'bland' 'bloated' 'blood' 'body'
 'body’s' 'boiling' 'boost' 'boosting' 'boredom' 'box' 'brain' 'bread'
 'breakfast' 'broccoli' 'brussels' 'buildup' 'calcium' 'calciumrich'
 'calories' 'carbohydrates' 'carbs' 'carrots' 'certain' 'change' 'changes'
 'charge' 'cheating' 'chemical' 'chicken' 'chili' 'choices' 'claiming'
 'cognitive' 'come' 'common' 'completely' 'complex' 'complicated'
 'computer' 'conflicting' 'considered' 'continue' 'contribute' 'control'
 'cook' 'cooking' 'cope' 'could' 'covid19' 'cravings' 'cut' 'cutting'
 'daily' 'dangerous' 'day' 'dehydrated—causing' 'dense' 'deplete'
 'depression' 'depriving' 'diabetes' 'diet' 'dietary' 'diets' 'difference'
 'difficult' 'difficulties' 'dinner—but' 'disease' 'diseases' 'dishes'
 'doesn

# Vocabulary creation

In [499]:
z=0
vocabulary={}
for word in filtered_sentence2:
    vocabulary[word]=z
    z=z+1

In [500]:
len(vocabulary)

377

# prior probabilities of all "labels", i.e. words in vocabulary

In [501]:
prior=[0]*len(vocabulary)

In [502]:
for word in filtered_sentence:
    prior[vocabulary[word]] =prior[vocabulary[word]]+1

In [503]:
prior=np.array(prior)

In [504]:
total_counts_in_class=prior

In [505]:
total_counts_in_class[:10]

array([1, 2, 2, 1, 1, 1, 2, 2, 5, 1])

In [506]:
prior=prior/577

In [507]:
prior.sum()

0.9999999999999998

# class-conditional probabilities of all words

In [508]:
len(total_counts_in_class)

377

In [509]:
total_counts_in_class=[total_counts_in_class]*len(vocabulary)

In [510]:
total_counts_in_class=np.array(total_counts_in_class)

In [511]:
total_counts_in_class.shape

(377, 377)

In [512]:
total_counts_in_class[:10]

array([[1, 2, 2, ..., 1, 2, 2],
       [1, 2, 2, ..., 1, 2, 2],
       [1, 2, 2, ..., 1, 2, 2],
       ...,
       [1, 2, 2, ..., 1, 2, 2],
       [1, 2, 2, ..., 1, 2, 2],
       [1, 2, 2, ..., 1, 2, 2]])

In [513]:
class_prob=np.zeros((len(vocabulary),len(vocabulary)))

In [514]:
class_prob

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [515]:
def preprocess(x):
    x=x.split()
    table = str.maketrans('', '', string.punctuation)
    x = [w.translate(table) for w in x]
    x = [word.lower() for word in x]
    final = [] 
    for w in x: 
        if w not in stop_words: 
            final.append(w)
    x=np.array(final)
    x=np.unique(x)
    return x
    

In [516]:
def word_to_vocabulary(x):
    final=[]
    for word in x:
        if word in vocabulary:
            final.append(vocabulary[word])
    return final

In [517]:
for sent in train.text:
    x=sent
    words=preprocess(x)
    words_vec=word_to_vocabulary(words)
    for i in words_vec:
        class_prob[i][words_vec]=class_prob[i][words_vec]+1

In [518]:
class_prob=class_prob/total_counts_in_class

In [519]:
class_prob[:10]

array([[1. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 1. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 1. , ..., 0. , 0.5, 0. ],
       ...,
       [0. , 0. , 0. , ..., 0. , 0. , 0.5],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ]])

# replacing zero probability to 0.1

In [520]:
class_prob[class_prob==0]=0.1

In [521]:
class_prob

array([[1. , 0.1, 0.1, ..., 0.1, 0.1, 0.1],
       [0.1, 1. , 0.1, ..., 0.1, 0.1, 0.1],
       [0.1, 0.1, 1. , ..., 0.1, 0.5, 0.1],
       ...,
       [0.1, 0.1, 0.1, ..., 1. , 0.1, 0.1],
       [0.1, 0.1, 0.5, ..., 0.1, 1. , 0.1],
       [0.1, 0.1, 0.1, ..., 0.1, 0.1, 1. ]])

# calculating the most likely word

In [522]:
vector_to_word=dict([(y,x) for x,y in vocabulary.items()])
    

In [523]:
vector_to_word[78]

'cut'

In [537]:
prob=[]
y_pred=[]
for sent in test.text:
    x=preprocess(sent)
    words=word_to_vocabulary(x)
    pred=1
    for i in words:
        pred=pred*class_prob[:,i]
    pred=prior*pred
    pred2=np.argmax(pred)
    prob.append(pred[pred2])
    y_pred.append(vector_to_word[pred2])

# Prediction

In [538]:
print(y_pred)

['healthy', 'diet', 'foods', 'diet', 'food', 'energy', 'foods', 'foods', 'eating', 'food']


# Confidence

In [539]:
print(prob)

[0.00016175621028307339, 0.007427581084426837, 1.6880866100970088e-05, 0.0038513383400731746, 0.0020797227036395147, 0.0025996533795493936, 3.2495667244367427e-06, 1.719347473246953e-05, 0.0010398613518197576, 0.0011554015020219526]


In [527]:
test.text[0]

'Eating healthy food is important for maintainng good _____'

In [528]:
test.text

0    Eating healthy food is important for maintainn...
1       Following a healthy diet will boost your _____
2    Avoid eating chemical additives, added sugars ...
3    Your diet should be rich of vitamins D,K, calc...
4    The healthier the food you eat, the better you...
5    Dehydration causes tiredness, low energy and h...
6    People with kidney disease should avoid eating...
7    We should avoid eating transfats. Eating healt...
8    Mindless eating is often caused by eating alon...
9    Eating more junk food will make you feel uncom...
Name: text, dtype: object